/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.relation_2_1;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Francisco
 */
public class Activity_4 extends javax.swing.JFrame {

    private JLabel labelMessage = new JLabel();
    /**
     * Creates new form Activity_1
     */
    public Activity_4() {
        initComponents();
        
        this.setBounds(0, 0, 500, 500);
        this.setLayout(null);
        
        labelMessage.setText("Stay strong");
        labelMessage.setFont(new Font("Arial", 1, 17));
        labelMessage.setHorizontalAlignment(SwingConstants.CENTER);
        labelMessage.setBounds(0, 200, 500, 50);
        this.add(labelMessage);

        labelMessage.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                
                labelMessage.setFont(new Font("Times New Roman", 1, 17));
            }
        });
        
        labelMessage.addMouseListener(new MouseAdapter() {
            public void mouseExited(MouseEvent evt) {
                
                labelMessage.setFont(new Font("Arial", 1, 17));
                labelMessage.setOpaque(false);
                labelMessage.setForeground(new Color(0, 0, 0));
                
            }
        });
        
        labelMessage.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent evt) {
                
                labelMessage.setOpaque(true);
                labelMessage.setBackground(new Color(0, 0, 0));
                labelMessage.setForeground(new Color(245, 245, 245));
            }
        });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
