/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.relation_2_1;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Francisco
 */
public class Activity_1 extends javax.swing.JFrame {

    private JButton boton1 = new JButton();
    private JButton boton2 = new JButton();
    private JButton boton3 = new JButton();
    /**
     * Creates new form Activity_1
     */
    public Activity_1() {
        initComponents();
        
        this.setBounds(0, 0, 500, 500);
        this.setLayout(null);
        
        crearBotones();
        
        boton1.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent evt) {
                boton1Pulsado(evt);
            }
        });

        boton2.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent evt) {
                boton2Pulsado(evt);
            }
        });

        boton3.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent evt) {
                boton3Pulsado(evt);
            }
        });
    }

    public void crearBotones() {
    
        boton1.setText("Botón 1");
        boton1.setBounds(40, 20, 100, 30);
        boton1.setBackground(new Color(57, 62, 65));
        boton1.setForeground(new Color(211, 208, 203));
        boton1.setFocusPainted(false);
        boton1.setFont(new Font("Arial",1, 15));
        this.add(boton1);

        boton2.setText("Botón 2");
        boton2.setBounds(190, 20, 100, 30);
        boton2.setBackground(new Color(57, 62, 65));
        boton2.setForeground(new Color(211, 208, 203));
        boton2.setFocusPainted(false);
        boton2.setFont(new Font("Arial",1, 15));
        this.add(boton2);

        boton3.setText("Botón 3");
        boton3.setBounds(340, 20, 100, 30);
        boton3.setBackground(new Color(57, 62, 65));
        boton3.setForeground(new Color(211, 208, 203));
        boton3.setFocusPainted(false);
        boton3.setFont(new Font("Arial",1, 15));
        this.add(boton3);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    private void boton1Pulsado(java.awt.event.ActionEvent evt) {                                         


        
    }
    
    private void boton2Pulsado(java.awt.event.ActionEvent evt) {                                         
        

        
    }
    
    private void boton3Pulsado(java.awt.event.ActionEvent evt) {                                         

        
        
    }  

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
