/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rel1t4_frb;

import javax.swing.*;

/**
 *
 * @author Propietario
 */
public class Ejercicio5 extends javax.swing.JPanel {

    SpringLayout layout = new SpringLayout();
    JMenuBar menuBar = new JMenuBar();
    JMenuItem itemInsertar = new JMenuItem("Insertar");
    JMenuItem itemBorrar = new JMenuItem("Borrar");
    JMenuItem itemMostrar = new JMenuItem("Mostrar");
    JMenuItem itemBuscar = new JMenuItem("Buscar");
    JMenuItem itemActualizar = new JMenuItem("Actualizar");

    /**
     * Creates new form Ejercicio5
     */
    public Ejercicio5() {
        initComponents();
        
        this.setLayout(layout);
        
        menuBar.add(itemInsertar);
        menuBar.add(itemBorrar);
        menuBar.add(itemMostrar);
        menuBar.add(itemBuscar);
        menuBar.add(itemActualizar);
        this.add(menuBar);
        
        layout.putConstraint(SpringLayout.WEST, menuBar, 0, SpringLayout.WEST, this);
        layout.putConstraint(SpringLayout.NORTH, menuBar, 0, SpringLayout.NORTH, this);
        layout.putConstraint(SpringLayout.EAST, menuBar, 0, SpringLayout.EAST, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
