/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.rel1t4_frb;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SpringLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Propietario
 */
public class PanelMostrar extends javax.swing.JPanel {

    private Connection conexion;
    String baseDeDatos = "relaciont5";
    
    DefaultTableModel modeloTabla = new DefaultTableModel();
    JTable tablaMascotas = new JTable(modeloTabla);
    JScrollPane scrollTabla = new JScrollPane(tablaMascotas);
    /**
     * Creates new form PanelMostrar
     */
    public PanelMostrar() throws SQLException {
        initComponents();
        
        conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+baseDeDatos+"?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","root");
        
        SpringLayout layout = new SpringLayout();
        this.setLayout(layout);
        this.setPreferredSize(new Dimension(480,300));
        
        scrollTabla.setPreferredSize(new Dimension(480,300));
        this.add(scrollTabla);
        layout.putConstraint(SpringLayout.WEST, scrollTabla, 0, SpringLayout.WEST, this);
        layout.putConstraint(SpringLayout.NORTH, scrollTabla, 0, SpringLayout.NORTH, this);
        
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Tipo");
        modeloTabla.addColumn("Edad");
        modeloTabla.addColumn("Descripción");
        modeloTabla.addColumn("Raza");
        
        recogerDatosTabla();
        
        tablaMascotas.getColumnModel().getColumn(3).setPreferredWidth(250);
        tablaMascotas.setDefaultEditor(Object.class, null);
        
    }
    
    public void recogerDatosTabla() {

        String consultaRecoger = "SELECT * FROM mascota";

        try {
            
            Statement consulta = conexion.createStatement();
            ResultSet resultado = consulta.executeQuery(consultaRecoger);

            while (resultado.next()) {
                
                modeloTabla.addRow(new Object[]{ resultado.getString("nombre"), resultado.getString("tipo"), resultado.getInt("edad"), resultado.getString("descripcion"), resultado.getString("raza")});
            
            }

        } catch (SQLException ex) {
            
            Logger.getLogger(Ejercicio2.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
