/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.relation_3_1_franciscorb;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import static javax.swing.GroupLayout.Alignment.BASELINE;
import static javax.swing.GroupLayout.Alignment.LEADING;

/**
 *
 * @author Propietario
 */
public class Activity_7 extends javax.swing.JFrame {

    JPanel panelMain = new JPanel();
    
    JLabel labelFind = new JLabel("Find What: ");
    JTextField inputFind = new JTextField(15);
    JCheckBox checkMatchCase = new JCheckBox("Match Case");
    JCheckBox checkWrapAround = new JCheckBox("Wrap Around");
    JCheckBox checkWholeWords = new JCheckBox("Whole Words");
    JCheckBox checkSearchBackwards = new JCheckBox("Search Backwards");
    JButton buttonFind = new JButton("Find");
    JButton buttonCancel = new JButton("Cancel");
    /**
     * Creates new form Activity_3
     */
    public Activity_7() { // Exercise done with the help of the code from the official Java page
        initComponents();

        this.setLayout(null);
        this.setBounds(0, 0, 515, 340);
        this.add(panelMain);

        GroupLayout layout = new GroupLayout(panelMain);
        panelMain.setLayout(layout);
        panelMain.setBounds(0, 0, 500, 300);
        
        // Space is added between components
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);
        
        layout.setHorizontalGroup( // The components are configured horizontally (the columns)
            layout.createSequentialGroup() // A button group is created
                .addComponent(labelFind) // Search label is added for the first column
                .addGroup(layout.createParallelGroup(LEADING) // Another group is created for another column
                    .addComponent(inputFind) // The textField is added
                    .addGroup(layout.createSequentialGroup() // Inside this column there will be 2 more columns
                        .addGroup(layout.createParallelGroup(LEADING) // The first one with the two checkboxes on the left
                            .addComponent(checkMatchCase)
                            .addComponent(checkWholeWords))
                        .addGroup(layout.createParallelGroup(LEADING) // The second one with the two checkboxes on the right
                            .addComponent(checkWrapAround)
                            .addComponent(checkSearchBackwards))))
                .addGroup(layout.createParallelGroup(LEADING) // In the last column the buttons are added
                    .addComponent(buttonFind)
                    .addComponent(buttonCancel))
        );

        layout.setVerticalGroup( // The components are configured vertically (the rows)
            layout.createSequentialGroup() // A button group is created
                .addGroup(layout.createParallelGroup(BASELINE) // It is configured to be added in parallel
                    // The entire first row is added
                    .addComponent(labelFind) 
                    .addComponent(inputFind)
                    .addComponent(buttonFind))
                .addGroup(layout.createParallelGroup(LEADING) // Another group is created for the rows below
                    .addGroup(layout.createSequentialGroup() // A button group is created
                        .addGroup(layout.createParallelGroup(BASELINE)  // It is configured to be added in parallel in a new group
                            // Second row is added
                            .addComponent(checkMatchCase)
                            .addComponent(checkWrapAround)
                            .addComponent(buttonCancel))
                        .addGroup(layout.createParallelGroup(BASELINE) // It is configured to be added in parallel in another group
                            // Third row added
                            .addComponent(checkWholeWords)
                            .addComponent(checkSearchBackwards)))
                )
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity_7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
