/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.relation_3_1_franciscorb;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Propietario
 */
public class Activity_5 extends javax.swing.JFrame {

    JPanel panelMain = new JPanel();

    JButton button1 = new JButton("Button 1");
    JButton button2 = new JButton("Button 2");
    JButton button3 = new JButton("Button 3");
    JButton button4 = new JButton("Long-named Button 4");
    JButton button5 = new JButton("5");

    /**
     * Creates new form Activity_3
     */
    public Activity_5() {
        initComponents();

        this.setLayout(null);
        this.setBounds(0, 0, 500, 300);
        this.add(panelMain);

        panelMain.setLayout(new GridBagLayout());
        panelMain.setBounds(0, 0, 500, 300);

        GridBagConstraints gridOptions = new GridBagConstraints();
        
        gridOptions.gridx = 0;
        gridOptions.gridy = 0;
        gridOptions.gridwidth = 1;
        gridOptions.gridheight = 1;
        gridOptions.fill = GridBagConstraints.BOTH;
        panelMain.add(button1, gridOptions);
        
        gridOptions.gridx = 1;
        gridOptions.gridy = 0;
        gridOptions.gridwidth = 1;
        gridOptions.gridheight = 1;
        panelMain.add(button2, gridOptions);
        
        gridOptions.gridx = 2;
        gridOptions.gridy = 0;
        gridOptions.gridwidth = 1;
        gridOptions.gridheight = 1;
        panelMain.add(button3, gridOptions);
        
        gridOptions.gridx = 0;
        gridOptions.gridy = 1;
        gridOptions.gridwidth = 3;
        gridOptions.gridheight = 2;
        gridOptions.ipady = 40;
        panelMain.add(button4, gridOptions);
        
        gridOptions.gridx = 1;
        gridOptions.gridy = 3;
        gridOptions.gridwidth = 2;
        gridOptions.gridheight = 1;
        gridOptions.ipady = 0;
        gridOptions.insets = new Insets(10,0,0,0); 
        panelMain.add(button5, gridOptions);
        
        button1.setBackground(new Color(175, 246, 249));
        button2.setBackground(new Color(206, 249, 175));
        button3.setBackground(new Color(249, 175, 183));
        button4.setBackground(new Color(206, 249, 175));
        button5.setBackground(new Color(243, 249, 175));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity_5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
