/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.relation_3_1_franciscorb;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Propietario
 */
public class Activity_3 extends javax.swing.JFrame {

    JPanel panelMain = new JPanel();
    JPanel panelButtons = new JPanel();
    JPanel panelText = new JPanel();
    JButton button1 = new JButton("Button 1");
    JButton button2 = new JButton("Button 2");
    JButton button3 = new JButton("Button 3");
    JTextField inputText = new JTextField();
    JComboBox<String> listOptions = new JComboBox();
    /**
     * Creates new form Activity_3
     */
    public Activity_3() {
        initComponents();
        
        this.setLayout(null);
        this.setBounds(0, 0, 500, 300);
        this.add(panelMain);
        
        
        panelMain.setLayout(new CardLayout());
        panelMain.setBounds(0, 0, 500, 300);
        
        
        button1.setBounds(50, 100, 100, 40);
        button2.setBounds(200, 100, 100, 40);
        button3.setBounds(350, 100, 100, 40);
        
        
        listOptions.setBounds(150, 20, 200, 50);
        listOptions.addItem("Card with JButtons");
        listOptions.addItem("Card with JTextField");
        panelMain.add(listOptions);
        
        
        inputText.setBounds(150, 100, 200, 40);
        
        
        panelButtons.setBounds(0, 200, 300, 400);
        panelButtons.add(button1);
        panelButtons.add(button2);
        panelButtons.add(button3);
        panelButtons.setLayout(null);
        panelMain.add(panelButtons, "panelButtons");
       
        
        panelText.setBounds(0, 200, 300, 400);
        panelText.add(inputText);
        panelText.setLayout(null);
        panelMain.add(panelText, "panelText");
        
        
        //CardLayout layout = (CardLayout)(panelMain.getLayout());
        //layout.show(panelMain, "panelButtons");
        
        
        listOptions.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                
                CardLayout card = (CardLayout) (panelMain.getLayout());
                String selectedOption = (String) listOptions.getSelectedItem();
                
                if ("Card with JButtons".equals(selectedOption)) {
                    
                    card.show(panelMain, "panelButtons");
                    
                } else if ("Card with JTextField".equals(selectedOption)) {
                    
                    card.show(panelMain, "panelText");
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
