/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.relation_3_1_franciscorb;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Propietario
 */
public class Activity_6 extends javax.swing.JFrame {

    JPanel panelMain = new JPanel();
    JPanel panelButtons = new JPanel();
    JPanel panelDown = new JPanel();

    JButton button1 = new JButton("Button 1");
    JButton button2 = new JButton("Button 2");
    JButton button3 = new JButton("Button 3");
    JButton button4 = new JButton("Long-named Button 4");
    JButton button5 = new JButton("5");
    JLabel labelHorizontal = new JLabel("Horizontal gap: ");
    JLabel labelVertical = new JLabel("Vertical gap: ");
    JComboBox<String> comboBoxHorizontal = new JComboBox<>();
    JComboBox<String> comboBoxVertical = new JComboBox<>();
    JButton buttonApply = new JButton("Apply gaps");
    /**
     * Creates new form Activity_3
     */
    public Activity_6() {
        initComponents();

        this.setLayout(null);
        this.setBounds(0, 0, 515, 340);
        this.add(panelMain);

        panelMain.setLayout(new BorderLayout());
        panelMain.setBounds(0, 0, 500, 300);
        
        button1.setBackground(new Color(175, 246, 249));
        button2.setBackground(new Color(206, 249, 175));
        button3.setBackground(new Color(249, 175, 183));
        button4.setBackground(new Color(206, 249, 175));
        button5.setBackground(new Color(243, 249, 175));
        
        panelButtons.setPreferredSize(new Dimension(500, 150));
        panelButtons.setLayout(new GridLayout(3,2));
        panelButtons.add(button1);
        panelButtons.add(button2);
        panelButtons.add(button3);
        panelButtons.add(button4);
        panelButtons.add(button5);
        panelMain.add(panelButtons, BorderLayout.NORTH);
        
        panelDown.setPreferredSize(new Dimension(500, 150));
        panelDown.setLayout(new GridLayout(2,3));
        panelDown.add(labelHorizontal);
        panelDown.add(labelVertical);
        panelMain.add(panelDown, BorderLayout.CENTER);
        
        comboBoxHorizontal.addItem("0");
        comboBoxHorizontal.addItem("10");
        panelDown.add(comboBoxHorizontal);
        
        comboBoxVertical.addItem("0");
        comboBoxVertical.addItem("10");
        panelDown.add(comboBoxVertical);
        
        panelDown.add(buttonApply);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
