/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.relation_3_1_franciscorb;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.*;

/**
 *
 * @author Propietario
 */
public class Activity_1 extends javax.swing.JFrame {
    
    JPanel panelMain = new JPanel();
    JPanel panelNorth = new JPanel();
    JPanel panelSouth = new JPanel();
    JButton buttonEast = new JButton();
    JButton buttonCenter = new JButton();
    JButton buttonWest = new JButton();
    /**
     * Creates new form Activity_1
     */
    public Activity_1() {
        
        initComponents();
        
        this.setBounds(0, 0, 615, 640);
        this.add(panelMain);
        
        panelMain.setBounds(0, 0, 600, 600);
        panelMain.setLayout(new BorderLayout());
        
        panelNorth.setPreferredSize(new Dimension(600, 200));
        panelNorth.setBackground(new Color(243, 249, 175));
        panelMain.add(panelNorth, BorderLayout.NORTH);
        
        panelSouth.setPreferredSize(new Dimension(600, 200));
        panelSouth.setBackground(new Color(179, 131, 191));
        panelMain.add(panelSouth, BorderLayout.SOUTH);
        
        buttonEast.setPreferredSize(new Dimension(200, 200));
        buttonEast.setBackground(new Color(175, 246, 249));
        buttonEast.setText("Button 1");
        panelMain.add(buttonEast, BorderLayout.EAST);
        
        buttonCenter.setPreferredSize(new Dimension(200, 200));
        buttonCenter.setBackground(new Color(249, 175, 183));
        buttonCenter.setText("Button 2");
        panelMain.add(buttonCenter, BorderLayout.CENTER);
        
        buttonWest.setPreferredSize(new Dimension(200, 200));
        buttonWest.setBackground(new Color(206, 249, 175));
        buttonWest.setText("Button 3");
        panelMain.add(buttonWest, BorderLayout.WEST);

        this.setVisible(true);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
