-- MySQL Script generated by MySQL Workbench
-- Sat Jan 11 18:35:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tareapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tareapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tareapp` DEFAULT CHARACTER SET utf8 ;
USE `tareapp` ;

-- -----------------------------------------------------
-- Table `tareapp`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tareapp`.`usuario` (
  `email` VARCHAR(255) NOT NULL,
  `contrasenia` VARCHAR(200) NOT NULL,
  `idioma_seleccionado` VARCHAR(45) NOT NULL DEFAULT 'Español',
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tareapp`.`lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tareapp`.`lista` (
  `idlistas` INT NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idlistas`),
  INDEX `fk_lista_usuario_idx` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_lista_usuario`
    FOREIGN KEY (`email`)
    REFERENCES `tareapp`.`usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tareapp`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tareapp`.`tarea` (
  `idtarea` INT NOT NULL,
  `completada` TINYINT(1) NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `prioridad` TINYINT NOT NULL,
  `fecha` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `idlistas` INT NOT NULL,
  PRIMARY KEY (`idtarea`),
  INDEX `fk_tarea_lista1_idx` (`idlistas` ASC) VISIBLE,
  CONSTRAINT `fk_tarea_lista1`
    FOREIGN KEY (`idlistas`)
    REFERENCES `tareapp`.`lista` (`idlistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
