-- MySQL Script generated by MySQL Workbench
-- Sun Mar 16 18:57:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tareapp_bbdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tareapp_bbdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tareapp_bbdd` DEFAULT CHARACTER SET utf8 ;
USE `tareapp_bbdd` ;

-- -----------------------------------------------------
-- Table `tareapp_bbdd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tareapp_bbdd`.`usuario` (
  `email` VARCHAR(255) NOT NULL,
  `contrasenia` VARCHAR(70) NOT NULL,
  `idioma_seleccionado` VARCHAR(45) NOT NULL DEFAULT 'Español',
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tareapp_bbdd`.`lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tareapp_bbdd`.`lista` (
  `idLista` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idLista`),
  INDEX `fk_lista_usuario_idx` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_lista_usuario`
    FOREIGN KEY (`email`)
    REFERENCES `tareapp_bbdd`.`usuario` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tareapp_bbdd`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tareapp_bbdd`.`tarea` (
  `idTarea` INT NOT NULL AUTO_INCREMENT,
  `completada` TINYINT(1) NOT NULL DEFAULT 0,
  `titulo` VARCHAR(50) NOT NULL,
  `prioridad` TINYINT NOT NULL DEFAULT 0,
  `fecha` DATE NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `idLista` INT NOT NULL,
  PRIMARY KEY (`idTarea`),
  INDEX `fk_tarea_lista1_idx` (`idLista` ASC) VISIBLE,
  CONSTRAINT `fk_tarea_lista1`
    FOREIGN KEY (`idLista`)
    REFERENCES `tareapp_bbdd`.`lista` (`idLista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tareapp_bbdd`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tareapp_bbdd`.`nota` (
  `idNota` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(250) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idNota`),
  INDEX `fk_nota_usuario1_idx` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_nota_usuario1`
    FOREIGN KEY (`email`)
    REFERENCES `tareapp_bbdd`.`usuario` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
