/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.exament3_frb;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SpringLayout;

/**
 *
 * @author Francisco
 */
public class Address_info extends javax.swing.JPanel {

    JLabel labelTitulo = new JLabel("Información domiciliaria ");
    JLabel labelCalle = new JLabel("Calle: ");
    JLabel labelNumero = new JLabel("Número: ");
    JLabel labelCiudad = new JLabel("Ciudad: ");
    JLabel labelCP = new JLabel("CP: ");
    
    JTextField inputCalle = new JTextField();
    JTextField inputNumero = new JTextField();
    JComboBox selectCiudad = new JComboBox();
    JTextField inputCP = new JTextField();
    /**
     * Creates new form Address_info
     */
    public Address_info() {
        initComponents();
        
                SpringLayout layout = new SpringLayout();
        this.setLayout(layout);
        this.setBounds(50, 50, 500, 400);
        this.setBackground(new Color(255,255,204));
        
        this.add(labelTitulo);
        this.add(labelCalle);
        this.add(labelNumero);
        this.add(labelCiudad);
        this.add(labelCP);
        
        this.add(inputCalle);
        this.add(inputNumero);
        this.add(selectCiudad);
        this.add(inputCP);
        
        labelTitulo.setPreferredSize(new Dimension(250, 30));
        labelCalle.setPreferredSize(new Dimension(100, 30));
        labelNumero.setPreferredSize(new Dimension(100, 30));
        labelCiudad.setPreferredSize(new Dimension(100, 30));
        labelCP.setPreferredSize(new Dimension(100, 30));
                
        inputCalle.setPreferredSize(new Dimension(100, 30));
        inputNumero.setPreferredSize(new Dimension(50, 30));
        selectCiudad.setPreferredSize(new Dimension(100, 30));
        inputCP.setPreferredSize(new Dimension(100, 30));
        
        selectCiudad.addItem("Ceuta");
        selectCiudad.addItem("Granada");
        selectCiudad.addItem("Almería");
        selectCiudad.addItem("Málaga");
        selectCiudad.addItem("Cádiz");
        selectCiudad.addItem("Tenerife");
        selectCiudad.addItem("Murcia");
     
        layout.putConstraint(SpringLayout.WEST, labelTitulo, 200, SpringLayout.WEST, this);
        layout.putConstraint(SpringLayout.NORTH, labelTitulo, 20, SpringLayout.NORTH, this);
        
        layout.putConstraint(SpringLayout.WEST, labelCalle, -50, SpringLayout.WEST, labelTitulo);
        layout.putConstraint(SpringLayout.NORTH, labelCalle, 50, SpringLayout.NORTH, labelTitulo);
        
        layout.putConstraint(SpringLayout.WEST, labelNumero, 0, SpringLayout.WEST, labelCalle);
        layout.putConstraint(SpringLayout.NORTH, labelNumero, 50, SpringLayout.NORTH, labelCalle);
        
        layout.putConstraint(SpringLayout.WEST, labelCiudad, 0, SpringLayout.WEST, labelNumero);
        layout.putConstraint(SpringLayout.NORTH, labelCiudad, 50, SpringLayout.NORTH, labelNumero);
        
        layout.putConstraint(SpringLayout.WEST, labelCP, 0, SpringLayout.WEST, labelCiudad);
        layout.putConstraint(SpringLayout.NORTH, labelCP, 50, SpringLayout.NORTH, labelCiudad);
        
        
        layout.putConstraint(SpringLayout.WEST, inputCalle, 100, SpringLayout.WEST, labelCalle);
        layout.putConstraint(SpringLayout.NORTH, inputCalle, 0, SpringLayout.NORTH, labelCalle);
        
        layout.putConstraint(SpringLayout.WEST, inputNumero, 100, SpringLayout.WEST, labelNumero);
        layout.putConstraint(SpringLayout.NORTH, inputNumero, 0, SpringLayout.NORTH, labelNumero);
        
        layout.putConstraint(SpringLayout.WEST, selectCiudad, 100, SpringLayout.WEST, labelCiudad);
        layout.putConstraint(SpringLayout.NORTH, selectCiudad, 0, SpringLayout.NORTH, labelCiudad);
        
        layout.putConstraint(SpringLayout.WEST, inputCP, 100, SpringLayout.WEST, labelCP);
        layout.putConstraint(SpringLayout.NORTH, inputCP, 0, SpringLayout.NORTH, labelCP);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
