/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exament2_frb;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Francisco
 */
public class Eje1 extends javax.swing.JFrame {

    JButton botonRosa = new JButton();
    JButton botonLimpiar = new JButton();
    JPanel panel = new JPanel();
    JLabel textoEventos = new JLabel();
    DefaultListModel<String> modelo = new DefaultListModel<String>();
    JList lista = new JList();
    /**
     * Creates new form Eje1
     */
    public Eje1() {
        initComponents();
        
        this.setBounds(0, 0, 500, 500);
        this.setLayout(null);
        
        panel.setBounds(0, 0, 500, 200);
        panel.setVisible(true);
        panel.setBackground(new Color(0, 200, 0));
        panel.setLayout(null);
        
        this.add(panel);

        lista.setBounds(10,220, 500,100);
        lista.setVisible(true);
        lista.setModel(modelo);
        this.add(lista);
        
        botonRosa.setText("Rosa");
        botonRosa.setBounds(10, 340, 70, 25);
        botonRosa.setVisible(true);
        this.add(botonRosa);
        
        botonLimpiar.setText("Rosa");
        botonLimpiar.setBounds(440, 340, 70, 25);
        botonLimpiar.setVisible(true);
        this.add(botonLimpiar);
        
        textoEventos.setText("Este es el panel que captura eventos");
        textoEventos.setBounds(250,25,255,25);
        textoEventos.setVisible(true);
        panel.add(textoEventos);
        
        botonRosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                
                panel.setBackground(new Color(200, 100, 100));
                modelo.addElement("Ha pulsado el botón rosa");
                lista.setModel(modelo);
            }
        });
        
        botonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                
                modelo.clear();
                lista.setModel(modelo);
            }
        });
        
        
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                
                panel.setBackground(Color.YELLOW);
                textoEventos.setForeground(Color.white);
                textoEventos.setOpaque(true);
                textoEventos.setBackground(Color.BLACK);
                modelo.addElement("Ha entrado del panel");
                lista.setModel(modelo);
            }
            
            public void mouseExited(java.awt.event.MouseEvent evt) {
                
                panel.setBackground(new Color(0, 200, 0));
                textoEventos.setForeground(Color.black);
                textoEventos.setOpaque(false);
                modelo.addElement("Ha salido del panel");
                lista.setModel(modelo);
                
            }
        });
        
       this.paint(this.getGraphics());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eje1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eje1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eje1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eje1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eje1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
