/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.relacion_2_franciscorb;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author Propietario
 */
public class Actividad_4 extends javax.swing.JFrame {

    private JPanel panelMenu = new JPanel();
    private PanelUsuario jpanelUsuario = new PanelUsuario();
    private PanelAplicacion jpanelAplicacion = new PanelAplicacion();
    private JButton botonUsuario = new JButton();
    private JButton botonAplicacion = new JButton();
    private JButton botonSalir = new JButton();
   
    /**
     * Creates new form Actividad_4
     */
    public Actividad_4() {
        initComponents();
        
        this.setBounds(0, 0, 500, 500);
        this.setLayout(null);
        
        panelMenu.add(jpanelUsuario);
        panelMenu.add(jpanelAplicacion);
        
        crearPanelMenu();
        
        panelMenu.setVisible(true);
        jpanelUsuario.setVisible(false);
        jpanelAplicacion.setVisible(false);
        
        this.paint(getGraphics());
        
        botonUsuario.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent evt) {
                botonUsuarioPulsado(evt);
            }
        });

        botonAplicacion.addActionListener(new ActionListener() {
  
            public void actionPerformed(ActionEvent evt) {
                botonAplicacionPulsado(evt);
            }
        });

        botonSalir.addActionListener(new ActionListener() {
            
            public void actionPerformed(ActionEvent evt) {
                botonSalirPulsado(evt);
            }
        });

    }
    
    public void crearPanelMenu() {

        panelMenu.setLayout(null);
        panelMenu.setBackground(new Color(245, 245, 245));
        panelMenu.setBounds(0, 0, 500, 500);
        this.add(panelMenu);

        botonUsuario.setText("Usuario");
        botonUsuario.setBounds(40, 20, 100, 30);
        botonUsuario.setBackground(new Color(57, 62, 65));
        botonUsuario.setForeground(new Color(211, 208, 203));
        botonUsuario.setFocusPainted(false);
        botonUsuario.setFont(new Font("Arial",1, 15));
        panelMenu.add(botonUsuario);

        botonAplicacion.setText("Aplicación");
        botonAplicacion.setBounds(190, 20, 100, 30);
        botonAplicacion.setBackground(new Color(57, 62, 65));
        botonAplicacion.setForeground(new Color(211, 208, 203));
        botonAplicacion.setFocusPainted(false);
        botonAplicacion.setFont(new Font("Arial",1, 15));
        panelMenu.add(botonAplicacion);

        botonSalir.setText("Salir");
        botonSalir.setBounds(340, 20, 100, 30);
        botonSalir.setBackground(new Color(57, 62, 65));
        botonSalir.setForeground(new Color(211, 208, 203));
        botonSalir.setFocusPainted(false);
        botonSalir.setFont(new Font("Arial",1, 15));
        panelMenu.add(botonSalir);

    }
    
    
    private void botonUsuarioPulsado(java.awt.event.ActionEvent evt) {                                         


        cambiarColorBoton(botonUsuario, botonAplicacion);
        jpanelUsuario.setVisible(true);
        jpanelAplicacion.setVisible(false);
        
    }
    
    private void botonAplicacionPulsado(java.awt.event.ActionEvent evt) {                                         
        
        cambiarColorBoton(botonAplicacion, botonUsuario);
        jpanelUsuario.setVisible(false);
        jpanelAplicacion.setVisible(true);
        
    }
    
    private void botonSalirPulsado(java.awt.event.ActionEvent evt) {                                         

        System.exit(0);
    }  

    public static void cambiarColorBoton(JButton botonAmarillo, JButton botonNormal) {
        
        botonAmarillo.setBackground(new Color(226, 192, 68));
        botonNormal.setBackground(new Color(57, 62, 65));
        
        botonAmarillo.setForeground(new Color(0, 0, 0));
        botonNormal.setForeground(new Color(211, 208, 203));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividad_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividad_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividad_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividad_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
