/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.relacion_2_franciscorb;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author Francisco
 */
public class Actividad_1 extends javax.swing.JFrame {

    private static JPanel panelGenerado = new javax.swing.JPanel(); // Crear panel

    /**
     * Creates new form Actividad_1
     */
    public Actividad_1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPoscionX = new javax.swing.JLabel();
        labelPosicionY = new javax.swing.JLabel();
        labelColorR = new javax.swing.JLabel();
        labelColorG = new javax.swing.JLabel();
        labelColorB = new javax.swing.JLabel();
        inputPoscionX = new javax.swing.JTextField();
        inputPosicionY = new javax.swing.JTextField();
        inputColorR = new javax.swing.JTextField();
        inputColorG = new javax.swing.JTextField();
        inputColorB = new javax.swing.JTextField();
        botonEnviar = new javax.swing.JButton();
        labelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPoscionX.setText("Posición X:");

        labelPosicionY.setText("Posición Y:");

        labelColorR.setText("Color R:");

        labelColorG.setText("Color G:");

        labelColorB.setText("Color B:");

        inputPoscionX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPoscionXActionPerformed(evt);
            }
        });

        inputColorR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputColorRActionPerformed(evt);
            }
        });

        botonEnviar.setText("Crear panel");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botonEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelPosicionY)
                                .addComponent(labelPoscionX)
                                .addComponent(labelColorR)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelColorB)
                                    .addComponent(labelColorG)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputPosicionY, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(inputColorG, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(inputColorR, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(inputPoscionX, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(inputColorB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 1, Short.MAX_VALUE))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPoscionX)
                    .addComponent(inputPoscionX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPosicionY)
                    .addComponent(inputPosicionY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelColorR)
                    .addComponent(inputColorR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelColorG)
                    .addComponent(inputColorG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelColorB)
                    .addComponent(inputColorB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputPoscionXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPoscionXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPoscionXActionPerformed

    private void inputColorRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputColorRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputColorRActionPerformed

    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        
        labelError.setText("");
        
        try {
            
            int posicionY = Integer.parseInt(inputPosicionY.getText());
            int posicionX = Integer.parseInt(inputPoscionX.getText());
            int colorR = Integer.parseInt(inputColorR.getText());
            int colorG = Integer.parseInt(inputColorG.getText());
            int colorB = Integer.parseInt(inputColorB.getText());

            crearPanel(posicionX, posicionY, colorR, colorG, colorB);
            
        } catch(Exception e) {
            
            labelError.setText("Error: Los datos introducidos no son correctos");
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_botonEnviarActionPerformed

    public void crearPanel(int posicionX, int posicionY, int colorR, int colorG, int colorB) {
                        
            // Dar propiedades
            panelGenerado.setSize(new Dimension(50, 50));
            panelGenerado.setPreferredSize(new Dimension(50, 50));
            panelGenerado.setBackground(new Color(colorR, colorG, colorB));
            panelGenerado.setLocation(posicionX, posicionY);
            
            // Añadir el panel
            panelGenerado.setVisible(true);
            this.add(panelGenerado);
            this.paint(getGraphics());
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividad_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividad_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividad_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividad_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnviar;
    private javax.swing.JTextField inputColorB;
    private javax.swing.JTextField inputColorG;
    private javax.swing.JTextField inputColorR;
    private javax.swing.JTextField inputPoscionX;
    private javax.swing.JTextField inputPosicionY;
    private javax.swing.JLabel labelColorB;
    private javax.swing.JLabel labelColorG;
    private javax.swing.JLabel labelColorR;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelPoscionX;
    private javax.swing.JLabel labelPosicionY;
    // End of variables declaration//GEN-END:variables
}
