/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.relacion_2_franciscorb;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Francisco
 */
public class Actividad_2 extends javax.swing.JFrame {

    private JPanel panelGenerado = new javax.swing.JPanel(); // Crear panel

    /**
     * Creates new form Actividad_2
     */
    public Actividad_2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelOpciones = new javax.swing.JLabel();
        inputOpcion1 = new javax.swing.JTextField();
        inputOpcion2 = new javax.swing.JTextField();
        inputOpcion3 = new javax.swing.JTextField();
        inputOpcion4 = new javax.swing.JTextField();
        botonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelOpciones.setText("Introduzca 4 opciones:");

        inputOpcion1.setToolTipText("fdgdfg");
        inputOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputOpcion1ActionPerformed(evt);
            }
        });

        inputOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputOpcion2ActionPerformed(evt);
            }
        });

        inputOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputOpcion3ActionPerformed(evt);
            }
        });

        inputOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputOpcion4ActionPerformed(evt);
            }
        });

        botonEnviar.setText("Crear opciones");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonEnviar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelOpciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputOpcion1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputOpcion4)
                    .addComponent(inputOpcion3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputOpcion2))
                .addContainerGap(589, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelOpciones)
                .addGap(10, 10, 10)
                .addComponent(inputOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(inputOpcion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEnviar)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputOpcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputOpcion1ActionPerformed

    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        
        panelGenerado.removeAll();
        
        crearPanel();
        
        JComboBox<String> inputSelect = new javax.swing.JComboBox<String>();
        inputSelect.addItem(inputOpcion1.getText());
        inputSelect.addItem(inputOpcion2.getText());
        inputSelect.addItem(inputOpcion3.getText());
        inputSelect.addItem(inputOpcion4.getText());
        panelGenerado.add(inputSelect);
                
        ArrayList<JRadioButton> opciones = new ArrayList<JRadioButton>();
        opciones.add(crearOpcion(inputOpcion1.getText()));
        opciones.add(crearOpcion(inputOpcion2.getText()));
        opciones.add(crearOpcion(inputOpcion3.getText()));
        opciones.add(crearOpcion(inputOpcion4.getText()));
        
        insertarOpcionesGrupo(opciones);

        paint(getGraphics());
    }//GEN-LAST:event_botonEnviarActionPerformed

    private void inputOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputOpcion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputOpcion3ActionPerformed

    private void inputOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputOpcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputOpcion2ActionPerformed

    private void inputOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputOpcion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputOpcion4ActionPerformed

    public JRadioButton crearOpcion(String texto) {
    
        JRadioButton opcion = new javax.swing.JRadioButton();
        opcion.setText(texto);
        
        return opcion;
    }
    
    public void crearPanel() {

        // Dar propiedades
        panelGenerado.setSize(new Dimension(400, 300));
        panelGenerado.setBackground(new Color(174, 216, 230));
        panelGenerado.setLocation(200, 25);

        // Añadir el panel
        panelGenerado.setVisible(true);
        this.add(panelGenerado);
    }
    
    public void insertarOpcionesGrupo(ArrayList<JRadioButton> opciones) {
    
        ButtonGroup grupoRadios = new javax.swing.ButtonGroup();
        
        for(int i = 0; i < opciones.size(); i++) {
        
            panelGenerado.add(opciones.get(i));
            grupoRadios.add(opciones.get(i));

        }
                
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividad_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividad_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividad_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividad_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnviar;
    private javax.swing.JTextField inputOpcion1;
    private javax.swing.JTextField inputOpcion2;
    private javax.swing.JTextField inputOpcion3;
    private javax.swing.JTextField inputOpcion4;
    private javax.swing.JLabel labelOpciones;
    // End of variables declaration//GEN-END:variables
}
