/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.relacion_2_franciscorb;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.SwingConstants;

/**
 *
 * @author Francisco
 */
public class PanelAplicacion extends javax.swing.JPanel {

    private ButtonGroup opcionesMetodoPago = new javax.swing.ButtonGroup();
    /**
     * Creates new form panelAplicacion
     */
    public PanelAplicacion() {
        initComponents();
        crearPanelAplicacion();
    }
    
    public void crearPanelAplicacion() {
        
        this.setLayout(null);
        this.setBackground(new Color(184, 184, 184));
        this.setBounds(0, 70, 500, 430);
        
        JLabel labelTitulo = new JLabel();
        labelTitulo.setText("Aplicación");
        labelTitulo.setFont(new Font("Arial", 1, 17));
        labelTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        labelTitulo.setBounds(0, 0, 500, 50);
        this.add(labelTitulo);
        
        JCheckBox appVscode = new JCheckBox();
        JCheckBox appNetBeans = new JCheckBox();
        JCheckBox appIntelliJ = new JCheckBox();
        JCheckBox appEclipse = new JCheckBox();        
        JCheckBox appUnity = new JCheckBox();
                                
        appVscode.setText("VScode");
        appVscode.setBounds(0, 50, 100, 50);
        appVscode.setFont(new Font("Arial", 1, 15));
        this.add(appVscode);
        
        appNetBeans.setText("NetBeans");
        appNetBeans.setBounds(100, 50, 100, 50);
        appNetBeans.setFont(new Font("Arial", 1, 15));
        this.add(appNetBeans);
        
        appIntelliJ.setText("IntelliJ");
        appIntelliJ.setBounds(200, 50, 100, 50);
        appIntelliJ.setFont(new Font("Arial", 1, 15));
        this.add(appIntelliJ);
        
        appEclipse.setText("Eclipse");
        appEclipse.setBounds(300, 50, 100, 50);
        appEclipse.setFont(new Font("Arial", 1, 15));
        this.add(appEclipse);
        
        appUnity.setText("Unity");
        appUnity.setBounds(400, 50, 100, 50);
        appUnity.setFont(new Font("Arial", 1, 15));
        this.add(appUnity);
        
        JLabel labelMetodoPago = new JLabel();
        labelMetodoPago.setText("Método de pago");
        labelMetodoPago.setHorizontalAlignment(SwingConstants.CENTER);
        labelMetodoPago.setFont(new Font("Arial", 1, 17));
        labelMetodoPago.setBounds(0, 100, 500, 50);
        this.add(labelMetodoPago);
        
        JRadioButton opcionTarjeta = new JRadioButton();
        opcionTarjeta.setText("Tarjeta");
        opcionTarjeta.setBounds(50, 150, 100, 50);
        opcionTarjeta.setFont(new Font("Arial", 1, 15));
                
        JRadioButton opcionBizum = new JRadioButton();
        opcionBizum.setText("Bizum");
        opcionBizum.setBounds(200, 150, 100, 50);
        opcionBizum.setFont(new Font("Arial", 1, 15));
                
        JRadioButton opcionPaypal = new JRadioButton();
        opcionPaypal.setText("PayPal");
        opcionPaypal.setBounds(350, 150, 100, 50);
        opcionPaypal.setFont(new Font("Arial", 1, 15));
        
        opcionesMetodoPago.add(opcionTarjeta);
        opcionesMetodoPago.add(opcionBizum);
        opcionesMetodoPago.add(opcionPaypal);
        
        this.add(opcionTarjeta);
        this.add(opcionBizum);
        this.add(opcionPaypal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
