/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.relacion_2_franciscorb;

import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author Francisco
 */
public class PanelUsuario extends javax.swing.JPanel {
    
    private JTextField inputNombre = new JTextField();
    private JTextField inputEdad = new JTextField();
    private JTextField inputApellidos = new JTextField();
    private JComboBox<String> selectGenero = new JComboBox<String>();
    private JTextArea TextAreaDescripcion = new JTextArea();
    /**
     * Creates new form panelUsuario
     */
    public PanelUsuario() {
        initComponents();
        this.crearPanelUsuario();
        
        // Comprobar nombre
        // String nombre = this.inputNombre.getText();
        // comprobarNombreApellido(nombre); // True si el nombre es correcto
        
        // Comprobar apellido
        // String apellido = this.inputNombre.getText();
        // comprobarNombreApellido(apellido); // True si el apellido es correcto
        
        // Comprobar edad
        // String edad = this.inputEdad.getText();
        // comprobarEdad(edad); // True si la edad es correcto
        
    }
    
    public void crearPanelUsuario() {
        
        this.setLayout(null);
        this.setBackground(new Color(184, 184, 184));
        this.setBounds(0, 70, 500, 430);
        
        JLabel labelTitulo = new JLabel();
        labelTitulo.setText("Información usuario");
        labelTitulo.setFont(new Font("Arial", 1, 17));
        labelTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        labelTitulo.setBounds(0, 0, 500, 50);
        this.add(labelTitulo);
        
        JLabel labelNombre = new JLabel();
        labelNombre.setText("Nombre*: ");
        labelNombre.setFont(new Font("Arial",1, 12));
        labelNombre.setBounds(30, 50, 100, 20);
        this.add(labelNombre);
        
        JLabel labelApellidos = new JLabel();
        labelApellidos.setText("Apellidos*: ");
        labelApellidos.setFont(new Font("Arial",1, 12));
        labelApellidos.setBounds(30, 100, 100, 20);
        this.add(labelApellidos);
        
        JLabel labelGenero = new JLabel();
        labelGenero.setText("Género*: ");
        labelGenero.setFont(new Font("Arial",1, 12));
        labelGenero.setBounds(265, 50, 100, 20);
        this.add(labelGenero);
        
        JLabel labelEdad = new JLabel();
        labelEdad.setText("Edad*: ");
        labelEdad.setFont(new Font("Arial",1, 12));
        labelEdad.setBounds(350, 100, 100, 20);
        this.add(labelEdad);
        
        inputNombre.setBounds(100, 45, 120, 30);
        this.add(inputNombre);
        
        selectGenero.setBounds(330, 45, 120, 30);
        selectGenero.addItem("Masculino");
        selectGenero.addItem("Femenino");
        selectGenero.addItem("No binario");
        this.add(selectGenero);
        
        inputApellidos.setBounds(100, 95, 200, 30);
        this.add(inputApellidos);

        inputEdad.setBounds(400, 95, 50, 30);
        this.add(inputEdad);
        
        JLabel labelDescripcion = new JLabel();
        labelDescripcion.setText("Descripción: ");
        labelDescripcion.setFont(new Font("Arial",1, 12));
        labelDescripcion.setBounds(30, 150, 100, 20);
        this.add(labelDescripcion);
        
        TextAreaDescripcion.setBounds(30, 180, 420, 150);
        this.add(TextAreaDescripcion);
        
    }
    
    public boolean comprobarNombreApellido(String nombreApellido) {
        
        if (nombreApellido.length() >= 1) {
        
            for (int i = 0 ; i < 10 ; i++) {
            
                if (nombreApellido.contains(String.valueOf(i))) {
                    return false;
                }
            }
            
        } else {
            
            return false;
        }

        return true;
    }
    
    public boolean comprobarEdad(String edad) {
        
        
        if (edad.length() >= 1) {
        
            try {

                Integer.parseInt(edad);
                return true;

            } catch(Exception e) {

                return false;

            }
            
        } else {
            
            return false;
        } 
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
