/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.relation_1_franciscorb;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author Francisco
 */
public class Activity_5 extends javax.swing.JFrame {

    /**
     * Creates new form Activity_5
     */
    public Activity_5() {
        initComponents();
        
        buttonGroupRadio.add(radioButtonA_Z);
        buttonGroupRadio.add(radioButtonZ_A);
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRadio = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        listVegetables = new javax.swing.JList<>();
        radioButtonA_Z = new javax.swing.JRadioButton();
        radioButtonZ_A = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listVegetables.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "lettuce", "onion", "pepper", "eggplant", "carrot" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listVegetables);

        radioButtonA_Z.setText("Sorted from A to Z");
        radioButtonA_Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonA_ZActionPerformed(evt);
            }
        });

        radioButtonZ_A.setText("Sorted from Z to A");
        radioButtonZ_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonZ_AActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radioButtonZ_A)
                    .addComponent(radioButtonA_Z))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(radioButtonA_Z)
                .addGap(18, 18, 18)
                .addComponent(radioButtonZ_A)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonA_ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonA_ZActionPerformed

        ArrayList<String> vegetablesSorted = convertArrayList();

        vegetablesSorted.sort( (a, b) -> { return -1 * a.compareTo(b); } );
        
        changeModel(vegetablesSorted);
    }//GEN-LAST:event_radioButtonA_ZActionPerformed

    private void radioButtonZ_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonZ_AActionPerformed

        ArrayList<String> vegetablesSorted = convertArrayList();

        vegetablesSorted.sort( (b, a) -> { return -1 * a.compareTo(b); } );
        
        changeModel(vegetablesSorted);

    }//GEN-LAST:event_radioButtonZ_AActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity_5().setVisible(true);
            }
        });
    }
    
    public ArrayList convertArrayList() {

        ListModel<String> dataList = listVegetables.getModel();
        ArrayList<String> vegetablesSorted = new ArrayList<>();
                
        for (int i = 0; i < dataList.getSize(); i++ ) {
        
            vegetablesSorted.add(dataList.getElementAt(i));
            
        }
    
        return vegetablesSorted;
    }
    
    public void changeModel(ArrayList<String> vegetablesSorted) {

        DefaultListModel<String> vegetable = new DefaultListModel<String>();
        
         for (int i = 0; i < vegetablesSorted.size(); i++ ) {

            vegetable.addElement(vegetablesSorted.get(i));

        }

            listVegetables.setModel(vegetable);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRadio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listVegetables;
    private javax.swing.JRadioButton radioButtonA_Z;
    private javax.swing.JRadioButton radioButtonZ_A;
    // End of variables declaration//GEN-END:variables
}
